---
- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2.7 for ansible to use'
      raw: sudo apt-get update && apt-get -y install python

- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - { role: nodejs, tags: ['nodejs'] }
    - { role: meteor, tags: ['meteor'] }
    - { role: fl-maps, tags: ['fl-maps'] }
